{'audio_file': {u'Comment': u'Processed by SoX',
                'audio_file_md5': 'f82363d69a3484846aae87113476424b',
                'bits_per_sample': 24,
                'channels': 1,
                'file_size': 211387,
                'format': 'FLAC',
                'input_file': './projects/test3/recording.flac',
                'md5sum': 'vzpygjWtKOS1ty2TpdqigQ==',
                'sample_rate': 44100,
                'seconds_length': 2,
                'total_sample': 105108L},
 'explicit': 'Clean',
 'filename': './projects/test3/260-James_Michael_DuPont-test3',
 'format': 'FLAC',
 'host_email_address': 'jamesmikedupont@google.com',
 'host_handle': 'h4ck3rm1k3',
 'host_name': 'James Michael DuPont',
 'host_number': '260',
 'intro_added': 'No',
 'license': 'http://creativecommons.org/licenses/by-sa/3.0/',
 'medium_summary': 'NONE',
 'project_dir': './projects/test3',
 'project_name': 'test3',
 'series': 'NONE',
 'short_summary': 'NONE',
 'shownotes_text': 'NONE',
 'slot': 'Next Available Slot',
 'tags': 'NONE',
 'title': 'NONE'}